import { chromium } from 'playwright-core';
const S = 'C:/Users/admin/AppData/Local/Temp/claude/c--Users-admin-Documents-GitHub-IPAmjWEB/38cfbce3-6a43-4a28-8535-87223e915ff5/scratchpad/ux/';
const b = await chromium.launch({ channel: 'chrome', headless: true });
const ctx = await b.newContext({ viewport: { width: 1360, height: 900 } });
const p = await ctx.newPage();
const errs = []; p.on('console', (m) => { if (m.type() === 'error' || m.type() === 'warning') errs.push(m.text()); }); p.on('pageerror', (e) => errs.push(String(e)));
await p.goto('http://127.0.0.1:8766/#q=' + encodeURIComponent('邉')); await p.waitForSelector('.glyph-card');
await p.evaluate(() => document.querySelector('.glyph-tools').scrollIntoView({ block: 'start' }));
await p.waitForTimeout(300); await p.screenshot({ path: S + 'n1-tools.png' });
await p.click('.diff-toggle'); await p.waitForTimeout(1200);
await p.evaluate(() => document.querySelector('.glyph-tools').scrollIntoView({ block: 'start' }));
await p.screenshot({ path: S + 'n2-diff.png' });
console.log('canvas', await p.locator('.glyph-card__face canvas').count(), 'default', await p.locator('.is-default-glyph').count());
await p.click('.glyph-tools__filters .chip:has-text("戸籍")'); await p.waitForTimeout(300);
console.log('status', await p.textContent('.glyph-tools__status'), 'visible', await p.locator('.char-panel .panel-section').nth(0).locator('.glyph-card:not(.is-filtered-out)').count());
await p.screenshot({ path: S + 'n3-filter.png' });
await p.click('#theme-toggle'); await p.waitForTimeout(800); await p.screenshot({ path: S + 'n4-dark.png' });
console.log(errs.join('\n'));
await b.close();
